### ISSUE TITLE
list_sort y list_filter

### ISSUE THREAD

**Issue by kevinszuchet** [kevinszuchet/so-guia-ejercicio3#1]
Cuando lee el archivo de entrada guarda bien las personas en la lista, pero despues a la hora de generar el de salida (donde tengo que filtrar la lista y ordenarla), la lista empieza a mostrar cualquier cosa.
Por ejemplo, en un archivo de entrada con:
- Persona A
- Persona B
- Persona C
Guarda bien las personas en la lista, y cuando esta en la iteración de la lista filtrada y ordenada, al hacer list_get siempre muestra la misma persona (en este caso 3 veces).
@natoszme

**Comment by natoszme** [comment]
Esto es lo que hablábamos ayer @LeandroCarbajales: al hacer persona = list_get, el puntero a la persona no varía entre las diferentes iteraciones

**Comment by LeandroCarbajales** [comment]
Fíjense que a la función agregarPersona están pasándole siempre la misma dirección, la de la variable unaPersona. Entonces cada vez que agregan una persona nueva están modificando lo que tenía la anterior y agregando ese mismo puntero a la lista de nuevo, por lo tanto quedan con una lista con 3 veces la misma direccion que tiene los datos de la última persona agregada.
Para trabajar con listas les recomiendo usar siempre memoria dinámica. Cada vez que quieran crear una nueva persona le pasan un puntero nuevo creado, en este caso, como "Persona* unaPersona = malloc(sizeof(Persona))"
Cuéntenme cómo les va con eso.

Saludos!
          Lean
